### ISSUE TITLE
请问能更新农业银行，光大银行，兴业银行app去广告规则吗

### ISSUE THREAD

**Issue by 28413761** [8680/GOODBYEADS#1]
请问能更新农业银行，光大银行，兴业银行app去广告规则吗

**Comment by 8680** [comment]
看了一眼农业银行app..也没瞧见广告啊:flushed:

**Comment by 28413761** [comment]
这广告不是一直都有，我刚试了下，今天确实没有，
但是之前一直都有 每次打开就是3秒的广告
但是我抓包一直抓不到广告连接




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月30日(星期六) 中午12:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [8680/GOODBYEADS] 请问能更新农业银行，光大银行，兴业银行app去广告规则吗 (Issue #1)





 
看了一眼农业银行app..也没瞧见广告啊😳
