### ISSUE TITLE
腾讯视频的有条规则会导致整个网页端的图片加载不出来

### ISSUE THREAD

**Issue by fengyinxia** [8680/GOODBYEADS#11]
||puui.qpic.cn^
如图
![5dc5056ee4ee3bac17d2b66bae6ac0f7870](https://github.com/8680/GOODBYEADS/assets/46144839/8d76161f-1ce1-40b5-b7fa-bca815a8571c)
这个规则还会导致视频播放页面的水印加载不出来，从而不断的闪烁

**Comment by 8680** [comment]
是的，所以要配合白名单使用，这条规则在白名单里放行了
 [#L5258](https://github.com/8680/GOODBYEADS/blob/27e6e9ee2cdb9abff9004095994d7e70164f3949/allow.txt#L5258)
