### ISSUE TITLE
微信相关必要域名被误杀

### ISSUE THREAD

**Issue by Paloexiz** [8680/GOODBYEADS#13]
😉与该情况类似的帖子：
`https://github.com/jdlingyu/ad-wars/issues/10`
————————————

- 误封1：微信Captcha人机验证：
`shminorshort.weixin.qq.com`

使用场景：
微信账号在新设备进行登录时，需要进行微信Captcha人机验证。

理想状况：
正常访问微信Captcha人机验证页面。

实际状况：
无法访问微信Captcha人机验证页面。

关于微信Captcha人机验证：
微信Captcha人机验证题目有两种，一种为“拼图”，另一种为“场景识别”。
与“拼图”题目相关的微信Captcha域名似乎被误杀了，但与“场景识别”相关的域名却似乎并没有被误杀（因为时间有限，没有多花时间检验状况，还请见谅）。

- 误封2：新设备账号登录验证（可能是这个域名）：
`support.weixin.qq.com`

使用场景：
在微信中使用新设备登录账号时，需要进行旧设备认证或其它认证方式。在选择旧设备认证选项后，会跳转到一个带有二维码的页面，需要使用已登录相关微信账号的旧设备去扫描该二维码，在扫描完二维码后，该页面跳转到验证提示页面（提示在旧设备上点击“认证”按钮）。

理想状况：
在上述使用场景的前提下，选择进行旧设备认证时，使用旧设备对新设备上显示的二维码进行扫描后，新设备上的二维码页面跳转至相应的验证提示页面。

实际状况：
在上述使用场景的前提下，选择进行旧设备认证时，使用旧设备对新设备上显示的二维码进行扫描后，新设备上的二维码页面并未跳转至相应的验证提示页面。

————————————
🧐 确定域名误杀的方法：
在出现异常状况后，对某个可能相关的域名拉入白名单先进行测试，如果状况依旧则再按照上述操作，直到状况正常。

🤗感谢您的项目为我带来的清净。

**Comment by Paloexiz** [comment]
抱歉，在您回复后我又重新检查了问题，发现是因为`shminorshort.weixin.qq.com`与`support.weixin.qq.com`的CNAMEs均指向`minorshort.weixin.qq.com`而导致被拦截的。
![image](https://github.com/8680/GOODBYEADS/assets/127204159/e24c6ff9-2761-4fec-9c5d-cbb5bee455af)

**Comment by 8680** [comment]
收到，已添加白名单😋
