### ISSUE TITLE
饿了么小程序误杀。

### ISSUE THREAD

**Issue by RainTsal** [8680/GOODBYEADS#15]
![Screenshot_2024-05-06-00-35-13-022_com.eg.android.AlipayGphone-edit.jpg](https://github.com/8680/GOODBYEADS/assets/78639461/1c5e39fc-38e6-4db1-9eb4-2b9679f3b8ee)

**Comment by 8680** [comment]
已添加放行规则，更新订阅或手动添加规则`@@||waimai-guide.ele.me^`到白名单
https://github.com/8680/GOODBYEADS/commit/708d8b054fe38e02a3a21e9cf1fa8378b3844292
