### ISSUE TITLE
请问拦截规则跟DNS拦截规则有什么区别

### ISSUE THREAD

**Issue by Style00** [8680/GOODBYEADS#19]
<img width="272" alt="Snipaste_2024-07-08_00-16-16" src="https://github.com/8680/GOODBYEADS/assets/62116123/eee0ab0d-b7fa-4888-be47-c9b23b35db3d">
两个都添加到Adguad拦截列表有问题吗

白名单添加到白名单列表

**Comment by 8680** [comment]
总的拦截规则是给客户端&浏览器插件用的，其中包含了DNS规则(可玩性高 过滤全)
DNS规则是给adguard home用的，是精简了总规则在adguard home上无法使用的规则(只针对拦截域名解析的请求)
如果你是用的客户端或插件过滤，那使用总的规则就可以了，adguard home 反之。
因为汇集了多个上游规则，可能会存在误杀的情况，建议添加白名单规则

**Comment by Style00** [comment]
好的  谢谢  感谢解答
