### ISSUE TITLE
麻烦能不能看看浦大喜奔的开屏广告

### ISSUE THREAD

**Issue by 28413761** [8680/GOODBYEADS#2]
麻烦能不能看看浦大喜奔，民生银行，动卡空间这几个APP的开屏广告
我用重写规则去掉广告了，
但是5秒倒计时还在，这个倒计时有办法消除吗

**Comment by 8680** [comment]
单靠去广告规则肯定是去除不了这个倒计时的

**Comment by 8680** [comment]
![photo_2022-04-30_13-16-31](https://user-images.githubusercontent.com/85273405/166092269-392dd3fb-e9ce-4cbd-b204-de27dee68d71.jpg)

可以使用创建快捷方式来跳过

**Comment by 28413761** [comment]
这个方式只能安卓使用吧，IOS好像不行吧.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月30日(星期六) 中午1:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [8680/GOODBYEADS] 麻烦能不能看看浦大喜奔的开屏广告 (Issue #2)





 

 
可以使用创建快捷方式来跳过
