### ISSUE TITLE
小米相关必要域名被误杀

### ISSUE THREAD

**Issue by Paloexiz** [8680/GOODBYEADS#21]
### 如题，涉及到的被封域名如下：
`data.sec.miui.com`

> 小米发布的部分App中的“隐私政策撤回同意”开关所需要请求的域名

————————————

### 🏕️使用场景：
![1](https://github.com/user-attachments/assets/337d324d-650f-4730-b210-2da8cb92d32a)

> 图1 - 小米发布的某个App中的“隐私政策撤回同意”开关

### 😆理想状况：
隐私政策撤回同意成功。

### 🤔实际状况：
提示“服务器异常”，撤回失败。如下图：
![2](https://github.com/user-attachments/assets/e83adbdf-daa4-4cd9-b83d-66e541111748)

> 图2 - “撤回失败”提示

————————————

### 🧐确定域名误杀的方法：
在出现异常状况后，对某个可能相关的域名拉入白名单先进行测试，如果状况依旧则再按照上述操作，直到状况正常。
实践过程如下图：
![3](https://github.com/user-attachments/assets/22d73540-5405-49fa-8468-fc719a3818aa)

> 图3 - 将域名`data.sec.miui.com`拉入白名单前

![4](https://github.com/user-attachments/assets/59edd700-4014-4a7a-8903-93c655023ee4)

> 图4 - 将域名`data.sec.miui.com`拉入白名单后

**😆将域名`data.sec.miui.com`拉入白名单后，功能恢复正常。**

### 🤔可考虑采纳的提议：
将域名`data.sec.miui.com`移出黑名单。

————————————
🤗感谢您的项目为我带来的便利与清净。

**Comment by 8680** [comment]
已添加至白名单https://github.com/8680/GOODBYEADS/commit/7682349e5732b210d599470c91cba99adc5328cf
