### ISSUE TITLE
DNS白名单无法添加到Adgurad Home的白名单中

### ISSUE THREAD

**Issue by liawt** [8680/GOODBYEADS#22]
首先感谢提供去重服务

https://github.com/8680/GOODBYEADS/issues/18
有提到白名单是提交到adguard home 过滤器>dns白名单

但是实际上ADG的这个DNS白名单白名单只能添加域名而不能添加txt订阅地址.
![image](https://github.com/user-attachments/assets/436c7244-20e0-4336-9990-ba50ddd392ef)

**Comment by 8680** [comment]
adguard home设置如图:
![image](https://github.com/user-attachments/assets/2440da30-c733-4807-906e-7e86d195f76d)
你使用的是mac adguard客户端吧，mac版的我没使用过，具体能否导入规则只能你自己摸索了
