### ISSUE TITLE
腾讯游戏登录及获取登录信息被误拦截

### ISSUE THREAD

**Issue by indoordiary** [8680/GOODBYEADS#23]
出现问题的host:
h.trace.qq.com

问题具现截图：
![S40725-21253816_com tencent tmgp sgame](https://github.com/user-attachments/assets/cd31e913-2a7a-4a79-a8a6-afe4e431be3d)

日志截图：
![屏幕截图 2024-07-25 213121](https://github.com/user-attachments/assets/cd0403a6-164c-43a9-90ce-1dfe78a2fb5f)

总结:
经查看过滤日志时并一条条测试发现，在自定义过滤规则列表里添加  @@||h.trace.qq.com^$important  放行问题host即可

**Comment by 8680** [comment]
已添加至白名单https://github.com/8680/GOODBYEADS/commit/817aa585a72a9eff0b868f6ba5c34245fcaccda6

**Comment by indoordiary** [comment]
> 已添加至白名单[817aa58](https://github.com/8680/GOODBYEADS/commit/817aa585a72a9eff0b868f6ba5c34245fcaccda6)

抱歉，刚才可能是缓存的原因，过了一会又误杀了。重新测了一下（已把第一次提交的host加入拦截名单），应该是要放行ap6.ssl.msdk.qq.com这个才行
![屏幕截图 2024-07-25 215541](https://github.com/user-attachments/assets/d4d8971d-7829-4a11-9e9f-b37af969147e)

**Comment by 8680** [comment]
已更正，后续麻烦再测试一下https://github.com/8680/GOODBYEADS/commit/e12b37b972ba99b91c697f1aaaaa3710e6011b38
