### ISSUE TITLE
抽什么风？

### ISSUE THREAD

**Issue by lim-kim930** [8680/GOODBYEADS#25]
好家伙，今天打开电脑一个网站都进不去，你可真行啊

**Comment by lim-kim930** [comment]
不知道你的上游哪里出了问题，排查下吧

**Comment by 8680** [comment]
![image](https://github.com/user-attachments/assets/8c6bfd07-99d1-4c0f-9fdd-c4b57eead276)
![image](https://github.com/user-attachments/assets/237f89a1-b32e-4aee-b67f-d50abf9025d1)
我建议你先自己排查一下！ 我这边目前使用的https://github.com/8680/GOODBYEADS/commit/272c1974f2de4be98a465c380bce0b34b08f55c8  无任何问题！

**Comment by lim-kim930** [comment]
![image](https://github.com/user-attachments/assets/f9451dcf-7f87-4484-aaea-2f52522e371f)

**Comment by lim-kim930** [comment]
拦截的规则是om^，在rule.txt里吗

**Comment by 8680** [comment]
![image](https://github.com/user-attachments/assets/3dce0255-32c6-48b4-aec3-2fd9b4d8832a)
![image](https://github.com/user-attachments/assets/91383121-e199-4b24-aee6-a9a3bc2bc2d0)
奇怪了 我这都正常的

**Comment by 8680** [comment]
你把规则删了 重新更新一下试试

**Comment by lim-kim930** [comment]
重新更新了下ok了，估计是ADGuard自动更新出问题了

**Comment by qq5460168** [comment]
> ![image](https://github.com/user-attachments/assets/3dce0255-32c6-48b4-aec3-2fd9b4d8832a)
> ![image](https://github.com/user-attachments/assets/91383121-e199-4b24-aee6-a9a3bc2bc2d0)
> 奇怪了 我这都正常的


我也是复刻大佬的项目
偶尔会这样貌似上游问题   我看过日记记录  下一次合并就自动删除了哪个 错误的规则
