### ISSUE TITLE
谷歌翻译

### ISSUE THREAD

**Issue by wengzhenquan** [8680/GOODBYEADS#26]
如 https://github.com/8680/GOODBYEADS/issues/21
使用场景：谷歌翻译
确定域名拦截或误杀的方法：为啥把谷歌翻译给拦截了？这都能拦截，太离谱了
提交规则:@@||translate.google.com^

**Comment by 8680** [comment]
![{E4064F3B-4613-46BC-9490-B91DF3CD7ECA}](https://github.com/user-attachments/assets/478f01b4-4a60-443a-8653-70e78c3effd4)
实测https://github.com/8680/GOODBYEADS/commit/61fc54c0dd15f0a41915f7aa8f249570430dc6df 没有问题..你有开别的规则吗

**Comment by wengzhenquan** [comment]
抱歉，是我搞错了，是那个人fork你代码，找错提issue的地方了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月5日(周四) 晚上6:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [8680/GOODBYEADS] 谷歌翻译 (Issue #26)




 
E4064F3B-4613-46BC-9490-B91DF3CD7ECA.png (view on web)
 实测61fc54c 没有问题..你有开别的规则吗

**Comment by wengzhenquan** [comment]
关闭

**Comment by wengzhenquan** [comment]
关闭
