### ISSUE TITLE
医院微信公召，预约挂号被拦截。

### ISSUE THREAD

**Issue by Lovest20018** [8680/GOODBYEADS#27]
**涉及规则:**白名单

**使用平台:**安卓手机

**描述问题:**微信公众号，比如浙二医院，预约挂号跳转后被拦截，看到白名单里有@@||shminorshort.weixin.qq.com^ 但我看了下，貌似我需要放行minorshort.weixin.qq.com 才可以访问

**提供截图:**

**提交规则:**@@||minorshort.weixin.qq.com^

**Comment by 8680** [comment]
已添加白名单https://github.com/8680/GOODBYEADS/commit/08321c97841f1f5d0c0dd3212e1e155ee47b255f
