### ISSUE TITLE
bilibili旧播放页面CC字幕功能被屏蔽

### ISSUE THREAD

**Issue by EdwardASU** [8680/GOODBYEADS#28]
**使用场景:**
浏览器内置adb添加规则
**描述问题:**
配合bilibili旧播放页脚本，使用旧播放页看视频的时候疑似CC字幕功能被屏蔽
被屏蔽相关域名：wss://broadcast.chat.bilibili.com
确定域名拦截或误杀的方法：根据控制台回馈信息显示，webhock链接失败，点击相关链接显示已被用户屏蔽

**Comment by 8680** [comment]
broadcast.chat.bilibili.com域名并没有在黑名单列表内，你确定使用的是本项目的规则吗😉

**Comment by EdwardASU** [comment]
> broadcast.chat.bilibili.com域名并没有在黑名单列表内，你确定使用的是本项目的规则吗😉

实测确实关闭了本项目规则就一切正常
![image](https://github.com/user-attachments/assets/987515a1-6c96-4949-835f-fc1dca3393e2)
怀疑是这个导致的误伤

**Comment by 8680** [comment]
![{86F0F60F-2C0E-44F2-BF8D-BAA8D8DD56F7}](https://github.com/user-attachments/assets/d224b019-9dfd-4d8c-8f62-8678fae6eb9b)

好像这个域名无关，我把chat.bilibili.com域名都拉入黑名单了，字幕还是能够正常生成

**Comment by 8680** [comment]
![{FEFEB330-44F2-4FEC-91B6-EB8F7F76310B}](https://github.com/user-attachments/assets/59edbe65-f047-451a-b722-a20f6dffb217)
我还特意下载了你所用的哔哩哔哩旧版本网页端来测试，貌似和这个域名无关

**Comment by 8680** [comment]
这个域名是用来屏蔽p2p上传的

**Comment by EdwardASU** [comment]
这边再测试了几次，确实不影响，不好意思麻烦你了

就有点奇怪，另一个脚本从其他域名获取字幕的时候，开启规则后几乎百分百没法跑到那个流程，而关闭后跑到获取流程反而更加简单
