### ISSUE TITLE
麻烦确认一下p站的封鎖规则

### ISSUE THREAD

**Issue by IM71** [8680/GOODBYEADS#3]
请问能更新对pornhub的规则吗？
目前无法进入觀看
谢谢

**Comment by 8680** [comment]
也罢，今天为你破个戒:banana:

**Comment by 8680** [comment]
经测试未发现你所描述的问题，建议检查一下是不是开了别的规则导致的。

**Comment by IM71** [comment]
> 经测试未发现你所描述的问题，建议检查一下是不是开了别的规则导致的。

好的 不好意思
我再确认一下
谢谢
