### ISSUE TITLE
携程手机版主页网址被误杀拦截

### ISSUE THREAD

**Issue by huskydsb** [8680/GOODBYEADS#30]
**涉及规则:**
https://raw.githubusercontent.com/8680/GOODBYEADS/master/data/rules/qx.list 中的 DOMAIN,m.ctrip.com,reject

**使用平台:**
IOS QX
**描述问题:**
携程主页被误杀
**提供截图:**
![1b4f32dc57f379addc74b7e5edf174c](https://github.com/user-attachments/assets/420302f9-84fe-4858-b612-bc51ec6a2475)

**提交规则:**

**Comment by huskydsb** [comment]
![4be49b13bba9c97e24d4b0627d23d71](https://github.com/user-attachments/assets/5a03c8fc-d797-4984-9ae6-a7494e825b57)

**Comment by 8680** [comment]
感谢提交，已处理
