### ISSUE TITLE
京东试用被误拦截

### ISSUE THREAD

**Issue by lengyuqingqiu** [8680/GOODBYEADS#4]
手机京东app，试用领取界面，免费申领可以进，但是商品详情页进不去，无法申请试用。

**Comment by 8680** [comment]
已添加白名单 https://github.com/8680/GOODBYEADS/commit/bfd701d8ce9f3159cd84e7c0fde365cc1f983390

**Comment by lengyuqingqiu** [comment]
试用可以用了，但是今日头条app启动时的京东广告拦不住了。

**Comment by lengyuqingqiu** [comment]
今日头条和头条极速版的京东，天猫广告拦不住。
