### ISSUE TITLE
合并脚本。

### ISSUE THREAD

**Issue by Dusk0531** [8680/GOODBYEADS#5]
你好 我借用你的项目使用了你们的规则合并脚本
但是几个小时后会显示如下页面
![Screenshot_2023-10-31-10-42-25-57_4d38fce200f96aeac5e860e739312e76](https://github.com/8680/GOODBYEADS/assets/130734435/97bb111e-83ff-45d3-8bba-858b4ba158bb)
工作流运行正常 https://github.com/Dusk0531/me/
请帮我查看项目脚本是否修改错误 只想构建用于自己使用
只修改了规则源以及更新时间

**Comment by 8680** [comment]
![Screenshot_2023-10-31-11-24-25-96_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/8680/GOODBYEADS/assets/85273405/bd32a52c-62d6-45c4-9e38-d2c57e4e6a7a)

这报错自己看一下吧

**Comment by Dusk0531** [comment]
谢谢&nbsp;解决了&nbsp;

千灯.
***@***.***




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月31日(周二) 中午11:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [8680/GOODBYEADS] 合并脚本。 (Issue #5)




 

 
这报错自己看一下吧
 
&mdash;
